apiVersion: v1
kind: Service
metadata:
  name: ems-frontend
  namespace: ems-app
spec:
  type: NodePort
  selector:
    app: ems-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32080
